name: Release Build

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build-linux-windows:
    name: Build on ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-pc-windows-gnu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename binary for release
        run: |
          EXT=""
          if [[ "${{ matrix.target }}" == *windows* ]]; then EXT=".exe"; fi
          mv target/${{ matrix.target }}/release/sysvitals$EXT sysvitals-${{ matrix.target }}$EXT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysvitals-${{ matrix.target }}
          path: sysvitals-${{ matrix.target }}*

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: sysvitals-${{ matrix.target }}*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary for release
        run: |
          mv target/${{ matrix.target }}/release/sysvitals sysvitals-${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysvitals-${{ matrix.target }}
          path: sysvitals-${{ matrix.target }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: sysvitals-${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 